/** @type {import('tailwindcss').Config} */
// Tokens del diseño "Dr. Martín Díaz" generado en Stitch.
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#001a41',
        'on-secondary-container': '#26687e',
        'secondary-container': '#a8e6ff',
        'primary-fixed-dim': '#adc7ff',
        'inverse-primary': '#adc7ff',
        'md-logo-blue': '#2B7DA3',
        'surface-tint': '#005bc0',
        secondary: '#23667b',
        'on-tertiary-fixed-variant': '#7c2e00',
        'on-secondary-fixed': '#001f28',
        'soft-blue-bg': '#F0F7FF',
        'surface-dim': '#d7d9e5',
        'surface-container-low': '#f1f3fe',
        'secondary-fixed-dim': '#92cfe7',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#d8e2ff',
        background: '#f9f9ff',
        'error-container': '#ffdad6',
        'surface-container-high': '#e6e8f3',
        'tertiary-container': '#c64f00',
        'on-primary-container': '#fefcff',
        'inverse-surface': '#2d3039',
        'surface-bright': '#f9f9ff',
        'outline-variant': '#c1c6d7',
        'on-primary-fixed-variant': '#004493',
        'clinical-white': '#FFFFFF',
        'secondary-fixed': '#b8eaff',
        'primary-container': '#0070ea',
        'on-surface-variant': '#414754',
        'on-surface': '#181c23',
        'tertiary-fixed-dim': '#ffb695',
        primary: '#0059bb',
        outline: '#717786',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'surface-container': '#ebedf9',
        'surface-container-lowest': '#ffffff',
        tertiary: '#9e3d00',
        'tertiary-fixed': '#ffdbcc',
        'surface-container-highest': '#e0e2ed',
        error: '#ba1a1a',
        'inverse-on-surface': '#eef0fb',
        'deep-navy': '#0A2540',
        'on-secondary-fixed-variant': '#004d61',
        'on-secondary': '#ffffff',
        surface: '#f9f9ff',
        'on-tertiary-fixed': '#351000',
        'surface-variant': '#e0e2ed',
        'on-background': '#181c23',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '20px',
        'stack-lg': '32px',
        'container-max': '1200px',
        'margin-desktop': '64px',
        'stack-sm': '8px',
        'stack-md': '16px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'system-ui', 'sans-serif'],
        caption: ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'system-ui', 'sans-serif'],
        'headline-lg': ['Manrope', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Manrope', 'system-ui', 'sans-serif'],
        'display-lg': ['Manrope', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
